In [1]:
import numpy as np
import pandas as pd
import requests as req
import time as time
import matplotlib.pyplot as plt
import os
import json
from citipy import citipy
from splinter import Browser
from bs4 import BeautifulSoup
from selenium import webdriver
from sys import platform
%matplotlib inline

In [2]:
usa_homicide_rates = pd.read_json("http://68.171.31.94:8001/search/1/pw/ProJEct2/table/Clean_homicideRates/db/1")
usa_unemployment_rate = pd.read_json("http://68.171.31.94:8001/search/1/pw/ProJEct2/table/Clean_usa_unemployment/db/1")
victim_services_statistical_report = pd.read_json("http://68.171.31.94:8001/search/1/pw/ProJEct2/table/Clean_vssr/db/1")

drug_poisoning_by_state = pd.read_json("http://68.171.31.94:8001/search/1/pw/ProJEct2/table/Clean_drug_poison_state/db/1")
drug_poisoning_per_county = pd.read_json("http://68.171.31.94:8001/search/1/pw/ProJEct2/table/Clean_drug_poison_county/db/1")

ct_personal_income = pd.read_json("http://68.171.31.94:8001/search/1/pw/ProJEct2/table/Clean_personal_inc/db/1")
ct_education_2014_2015 = pd.read_json("http://68.171.31.94:8001/search/1/pw/ProJEct2/table/Clean_ct_edu_2014_2015/db/1")
ct_unemployment = pd.read_json("http://68.171.31.94:8001/search/1/pw/ProJEct2/table/Clean_ct_unemployment/db/1")
ct_accidental_drug_deaths = pd.read_json("http://68.171.31.94:8001/search/1/pw/ProJEct2/table/Clean_acc_drug_deaths/db/1")

In [4]:
usa_homicide_rates.head(1)

     2009    2010    2011    2012    2013  Field7  Field8  ID    Weapon
0  6501.0  6115.0  6251.0  6404.0  5782.0     NaN     NaN   1  Handguns

In [5]:
usa_unemployment_rate.head(1)

,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,...,2011,2012,2013,2014,2015,2016,2017,2018,ID,Month
0,8.0,7.3,6.7,6.6,5.7,5.4,5.4,6.4,7.3,7.3,...,9.1,8.3,8.0,6.6,5.7,4.9,4.8,4.1,1,Jan

In [14]:
victim_services_statistical_report.head(1)

,Data Value,Footnote,ID,Indicator,Month,Percent Complete,Percent Pending Investigation,Period,State,State Name,Year
0,50880,None,8001,Number of Deaths,March,100,0.206368,12 month-ending,WI,Wisconsin,2016

In [9]:
drug_poisoning_by_state

,Age Group,Age-adjusted Rate,Crude Death Rate,Deaths,ID,Lower Confidence Limit for Age-adjusted Rate,Lower Confidence Limit for Crude Rate,Population,Race and Hispanic Origin,Sex,Standard Error for Age-adjusted Rate,Standard Error for Crude Rate,State,State Crude Rate in Range,US Age-adjusted Rate,US Crude Rate,Upper Confidence Limit for Age-adjusted Rate,Upper Confidence Limit for Crude Rate,Year
0,All Ages,3.8521,3.8148,169,1,3.2708,3.2396,4430143,All Races-All Origins,Both Sexes,0.29657,0.29344,Alabama,1.8â€“7.1,6.0570,6.0382,4.4334,4.3899,1999
1,All Ages,4.4857,4.4299,197,2,3.8588,3.8112,4447100,All Races-All Origins,Both Sexes,0.31985,0.31561,Alabama,1.8â€“7.1,6.1749,6.1882,5.1126,5.0485,2000
2,All Ages,4.8915,4.8348,216,3,4.2382,4.1900,4467634,All Races-All Origins,Both Sexes,0.33329,0.32896,Alabama,1.8â€“7.1,6.7922,6.8057,5.5447,5.4795,2001
3,All Ages,4.7619,4.7097,211,4,4.1177,4.0742,4480089,All Races-All Origins,Both Sexes,0.32868,0.32423,Alabama,1.8â€“7.1,8.1957,8.1766,5.4062,5.3452,2002
4,All Ages,4.4333,4.3744,197,5,3.8120,3.7635,4503491,All Races-All Origins,Both Sexes,0.31701,0.31166,Alabama,1.8â€“7.1,8.8765,8.8881,5.0547,4.9852,2003
5,All Ages,6.3542,6.2462,283,6,5.6105,5.5185,4530729,All Races-All Origins,Both Sexes,0.37944,0.37130,Alabama,1.8â€“7.1,9.3831,9.3660,7.0979,6.9740,2004
6,All Ages,6.3330,6.1928,283,7,5.5915,5.4713,4569805,All Races-All Origins,Both Sexes,0.37832,0.36813,Alabama,1.8â€“7.1,10.0699,10.0884,7.0745,6.9143,2005
7,All Ages,8.7498,8.5980,398,8,7.8842,7.7533,4628981,All Races-All Origins,Both Sexes,0.44162,0.43098,Alabama,7.1â€“10.2,11.4883,11.5373,9.6154,9.4427,2006
8,All Ages,11.0885,10.9355,511,9,10.1180,9.9874,4672840,All Races-All Origins,Both Sexes,0.49516,0.48376,Alabama,10.3â€“12.6,11.8775,11.9543,12.0590,11.8837,2007
9,All Ages,12.9811,12.8651,607,10,11.9366,11.8416,4718206,All Races-All Origins,Both Sexes,0.53292,0.52218,Alabama,12.6â€“16,11.8947,11.9864,14.0256,13.8885,2008
10,All Ages,13.6077,13.2410,630,11,12.5325,12.2071,4757938,All Races-All Origins,Both Sexes,0.54855,0.52754,Alabama,12.6â€“16,11.9388,12.0624,14.6828,14.2750,2009
11,All Ages,11.7688,11.4441,547,12,10.7700,10.4851,4779736,All Races-All Origins,Both Sexes,0.50959,0.48932,Alabama,10.3â€“12.6,12.2966,12.4144,12.7676,12.4032,2010
12,All Ages,11.7632,11.4934,552,13,10.7674,10.5346,4802740,All Races-All Origins,Both Sexes,0.50803,0.48919,Alabama,10.3â€“12.6,13.1852,13.2674,12.7589,12.4523,2011
13,All Ages,12.0706,11.6549,562,14,11.0569,10.6913,4822023,All Races-All Origins,Both Sexes,0.51722,0.49163,Alabama,10.3â€“12.6,13.1422,13.2208,13.0844,12.6185,2012
14,All Ages,12.7176,12.3714,598,15,11.6801,11.3798,4833722,All Races-All Origins,Both Sexes,0.52933,0.50590,Alabama,12.6â€“16,13.8005,13.9127,13.7551,13.3630,2013
15,All Ages,15.1532,14.9091,723,16,14.0265,13.8224,4849377,All Races-All Origins,Both Sexes,0.57484,0.55448,Alabama,12.6â€“16,14.6831,14.7574,16.2799,15.9959,2014
16,All Ages,15.6639,15.1472,736,17,14.5103,14.0529,4858979,All Races-All Origins,Both Sexes,0.58859,0.55833,Alabama,12.6â€“16,16.2923,16.3040,16.8176,16.2415,2015
17,All Ages,16.2075,15.5450,756,18,15.0268,14.4369,4863300,All Races-All Origins,Both Sexes,0.60241,0.56537,Alabama,16â€“52,19.7851,19.6925,17.3883,16.6531,2016
18,All Ages,7.4638,7.3626,46,19,5.2819,5.3903,624781,All Races-All Origins,Both Sexes,1.21170,1.08555,Alaska,7.1â€“10.2,6.0570,6.0382,10.2447,9.8206,1999
19,All Ages,7.1077,7.6563,48,20,5.2407,5.6452,626932,All Races-All Origins,Both Sexes,1.02971,1.10510,Alaska,7.1â€“10.2,6.1749,6.1882,9.4238,10.1512,2000
20,All Ages,9.3983,9.7836,62,21,7.1889,7.5010,633714,All Races-All Origins,Both Sexes,1.20475,1.24252,Alaska,7.1â€“10.2,6.7922,6.8057,12.0725,12.5421,2001
21,All Ages,12.1995,13.0772,84,22,9.7168,10.4309,642337,All Races-All Origins,Both Sexes,1.33512,1.42684,Alaska,10.3â€“12.6,8.1957,8.1766,15.1231,16.1905,2002
22,All Ages,12.7245,12.8005,83,23,10.0420,10.1955,648414,All Races-All Origins,Both Sexes,1.45104,1.40503,Alaska,12.6â€“16,8.8765,8.8881,15.9034,15.8681,2003
23,All Ages,12.7164,13.0444,86,24,10.1286,10.4338,659286,All Races-All Origins,Both Sexes,1.39682,1.40662,Alaska,12.6â€“16,9.3831,9.3660,15.7639,16.1097,2004
24,All Ages,11.3744,11.8450,79,25,8.9765,9.3778,666946,All Races-All Origins,Both Sexes,1.29691,1.33267,Alaska,10.3â€“12.6,10.0699,10.0884,14.2160,14.7625,2005
25,All Ages,11.0604,11.2542,76,26,8.6696,8.8670,675302,All Races-All Origins,Both Sexes,1.29844,1.29095,Alaska,10.3â€“12.6,11.4883,11.5373,13.9068,14.0863,2006
26,All Ages,10.0941,10.5836,72,27,7.8688,8.2810,680300,All Races-All Origins,Both Sexes,1.20552,1.24729,Alaska,7.1â€“10.2,11.8775,11.9543,12.7533,13.3282,2007
27,All Ages,18.1345,18.4739,127,28,14.9014,15.2609,687455,All Races-All Origins,Both Sexes,1.64954,1.63930,Alaska,16â€“52,11.8947,11.9864,21.3676,21.6870,2008
28,All Ages,17.8528,18.7439,131,29,14.7240,15.5341,698895,All Races-All Origins,Both Sexes,1.59631,1.63766,Alaska,16â€“52,11.9388,12.0624,20.9816,21.9537,2009
29,All Ages,11.5962,11.6863,83,30,9.1809,9.3081,710231,All Races-All Origins,Both Sexes,1.30471,1.28274,Alaska,10.3â€“12.6,12.2966,12.4144,14.4524,14.4870,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2832,All Ages,9.3367,9.3398,518,2833,8.5281,8.5355,5546166,All Races-All Origins,Both Sexes,0.41256,0.41037,Wisconsin,7.1â€“10.2,10.0699,10.0884,10.1453,10.1441,2005
2833,All Ages,10.6366,10.6317,593,2834,9.7736,9.7760,5577655,All Races-All Origins,Both Sexes,0.44031,0.43659,Wisconsin,10.3â€“12.6,11.4883,11.5373,11.4996,11.4874,2006
2834,All Ages,11.0976,11.0858,622,2835,10.2169,10.2146,5610775,All Races-All Origins,Both Sexes,0.44934,0.44450,Wisconsin,10.3â€“12.6,11.8775,11.9543,11.9783,11.9570,2007
2835,All Ages,10.6039,10.7428,606,2836,9.7490,9.8874,5640996,All Races-All Origins,Both Sexes,0.43621,0.43640,Wisconsin,10.3â€“12.6,11.8947,11.9864,11.4589,11.5981,2008
2836,All Ages,10.9348,11.1302,631,2837,10.0684,10.2617,5669264,All Races-All Origins,Both Sexes,0.44203,0.44309,Wisconsin,10.3â€“12.6,11.9388,12.0624,11.8012,11.9986,2009
2837,All Ages,10.9422,11.0779,630,2838,10.0723,10.2129,5686986,All Races-All Origins,Both Sexes,0.44385,0.44136,Wisconsin,10.3â€“12.6,12.2966,12.4144,11.8122,11.9430,2010
2838,All Ages,12.0766,12.2204,698,2839,11.1630,11.3138,5711767,All Races-All Origins,Both Sexes,0.46613,0.46255,Wisconsin,10.3â€“12.6,13.1852,13.2674,12.9902,13.1270,2011
2839,All Ages,12.2266,12.0844,692,2840,11.2961,11.1840,5726398,All Races-All Origins,Both Sexes,0.47472,0.45938,Wisconsin,10.3â€“12.6,13.1422,13.2208,13.1570,12.9848,2012
2840,All Ages,15.0285,14.9058,856,2841,13.9995,13.9073,5742713,All Races-All Origins,Both Sexes,0.52496,0.50947,Wisconsin,12.6â€“16,13.8005,13.9127,16.0574,15.9044,2013
2841,All Ages,15.0648,14.8153,853,2842,14.0288,13.8211,5757564,All Races-All Origins,Both Sexes,0.52857,0.50727,Wisconsin,12.6â€“16,14.6831,14.7574,16.1008,15.8095,2014
2842,All Ages,15.4719,15.2131,878,2843,14.4228,14.2068,5771337,All Races-All Origins,Both Sexes,0.53525,0.51342,Wisconsin,12.6â€“16,16.2923,16.3040,16.5210,16.2194,2015
2843,All Ages,19.2873,18.5855,1074,2844,18.1031,17.4739,5778708,All Races-All Origins,Both Sexes,0.60416,0.56712,Wisconsin,16â€“52,19.7851,19.6925,20.4714,19.6970,2016
2844,All Ages,4.0956,4.0669,20,2845,2.5017,2.4841,491780,All Races-All Origins,Both Sexes,0.91882,0.90938,Wyoming,1.8â€“7.1,6.0570,6.0382,6.3254,6.2809,1999
2845,All Ages,4.6054,4.4554,22,2846,2.8862,2.7922,493782,All Races-All Origins,Both Sexes,0.98469,0.94990,Wyoming,1.8â€“7.1,6.1749,6.1882,6.9727,6.7455,2000
2846,All Ages,4.5032,4.4475,22,2847,2.8221,2.7872,494657,All Races-All Origins,Both Sexes,0.96530,0.94822,Wyoming,1.8â€“7.1,6.7922,6.8057,6.8179,6.7336,2001
2847,All Ages,6.9214,6.7998,34,2848,4.7933,4.7090,500017,All Races-All Origins,Both Sexes,1.19565,1.16615,Wyoming,1.8â€“7.1,8.1957,8.1766,9.6720,9.5020,2002
2848,All Ages,5.9028,5.9588,30,2849,3.9532,4.0204,503453,All Races-All Origins,Both Sexes,1.08929,1.08793,Wyoming,1.8â€“7.1,8.8765,8.8881,8.4774,8.5066,2003
2849,All Ages,9.0935,9.0354,46,2850,6.6329,6.6151,509106,All Races-All Origins,Both Sexes,1.35994,1.33220,Wyoming,7.1â€“10.2,9.3831,9.3660,12.1679,12.0520,2004
2850,All Ages,4.9027,5.0568,26,2851,3.1728,3.3033,514157,All Races-All Origins,Both Sexes,0.97898,0.99172,Wyoming,1.8â€“7.1,10.0699,10.0884,7.2374,7.4094,2005
2851,All Ages,10.5619,10.5230,55,2852,7.9116,7.9273,522667,All Races-All Origins,Both Sexes,1.44873,1.41891,Wyoming,10.3â€“12.6,11.4883,11.5373,13.8153,13.6971,2006
2852,All Ages,12.2666,11.7784,63,2853,9.3830,9.0509,534876,All Races-All Origins,Both Sexes,1.57448,1.48394,Wyoming,10.3â€“12.6,11.8775,11.9543,15.7570,15.0697,2007
2853,All Ages,14.0453,13.5520,74,2854,10.9695,10.6413,546043,All Races-All Origins,Both Sexes,1.66440,1.57539,Wyoming,12.6â€“16,11.8947,11.9864,17.7162,17.0134,2008
2854,All Ages,10.9508,10.7171,60,2855,8.3154,8.1783,559851,All Races-All Origins,Both Sexes,1.44087,1.38358,Wyoming,10.3â€“12.6,11.9388,12.0624,14.1564,13.7951,2009
2855,All Ages,14.9556,15.0809,85,2856,11.8769,12.0461,563626,All Races-All Origins,Both Sexes,1.66261,1.63576,Wyoming,12.6â€“16,12.2966,12.4144,18.5884,18.6478,2010
2856,All Ages,15.2082,14.9606,85,2857,12.0775,11.9500,568158,All Races-All Origins,Both Sexes,1.69454,1.62271,Wyoming,12.6â€“16,13.1852,13.2674,18.9024,18.4990,2011
2857,All Ages,16.7507,17.0017,98,2858,13.5200,13.8028,576412,All Races-All Origins,Both Sexes,1.73782,1.71743,Wyoming,16â€“52,13.1422,13.2208,20.5208,20.7197,2012
2858,All Ages,17.2422,16.8195,98,2859,13.9167,13.6549,582658,All Races-All Origins,Both Sexes,1.78648,1.69902,Wyoming,16â€“52,13.8005,13.9127,21.1229,20.4975,2013
2859,All Ages,19.3823,18.6595,109,2860,15.6577,15.1565,584153,All Races-All Origins,Both Sexes,1.90026,1.78726,Wyoming,16â€“52,14.6831,14.7574,23.1068,22.1625,2014
2860,All Ages,16.4454,16.3793,96,2861,13.2241,13.2673,586107,All Races-All Origins,Both Sexes,1.72940,1.67170,Wyoming,16â€“52,16.2923,16.3040,20.2142,20.0019,2015
2861,All Ages,17.5871,16.9086,99,2862,14.1950,13.7425,585501,All Races-All Origins,Both Sexes,1.81892,1.69938,Wyoming,16â€“52,19.7851,19.6925,21.5453,20.5856,2016

In [15]:
drug_poisoning_per_county

,County,"Estimated Age-adjusted Death Rate, 16 Categories (in ranges)",FIPS,FIPS State,ID,Population,State,Year
0,"Steuben County, IN",8-9.9,18151,18,13826,34372,Indiana,2015
1,"Steuben County, IN",8-9.9,18151,18,13827,34116,Indiana,2016
2,"Sullivan County, IN",8-9.9,18153,18,13828,21758,Indiana,1999
3,"Sullivan County, IN",8-9.9,18153,18,13829,21756,Indiana,2000
4,"Sullivan County, IN",8-9.9,18153,18,13830,21771,Indiana,2001
5,"Sullivan County, IN",10-11.9,18153,18,13831,21792,Indiana,2002
6,"Sullivan County, IN",10-11.9,18153,18,13832,21801,Indiana,2003
7,"Sullivan County, IN",10-11.9,18153,18,13833,21809,Indiana,2004
8,"Sullivan County, IN",12-13.9,18153,18,13834,21689,Indiana,2005
9,"Sullivan County, IN",12-13.9,18153,18,13835,21540,Indiana,2006
10,"Sullivan County, IN",14-15.9,18153,18,13836,21558,Indiana,2007
11,"Sullivan County, IN",14-15.9,18153,18,13837,21550,Indiana,2008
12,"Sullivan County, IN",16-17.9,18153,18,13838,21483,Indiana,2009
13,"Sullivan County, IN",16-17.9,18153,18,13839,21411,Indiana,2010
14,"Sullivan County, IN",18-19.9,18153,18,13840,21237,Indiana,2011
15,"Sullivan County, IN",18-19.9,18153,18,13841,21215,Indiana,2012
16,"Sullivan County, IN",20-21.9,18153,18,13842,21174,Indiana,2013
17,"Sullivan County, IN",20-21.9,18153,18,13843,21003,Indiana,2014
18,"Sullivan County, IN",22-23.9,18153,18,13844,20928,Indiana,2015
19,"Sullivan County, IN",24-25.9,18153,18,13845,20802,Indiana,2016
20,"Switzerland County, IN",4-5.9,18155,18,13846,8965,Indiana,1999
21,"Switzerland County, IN",4-5.9,18155,18,13847,9129,Indiana,2000
22,"Switzerland County, IN",4-5.9,18155,18,13848,9465,Indiana,2001
23,"Switzerland County, IN",6-7.9,18155,18,13849,9711,Indiana,2002
24,"Switzerland County, IN",6-7.9,18155,18,13850,9722,Indiana,2003
25,"Switzerland County, IN",6-7.9,18155,18,13851,9863,Indiana,2004
26,"Switzerland County, IN",8-9.9,18155,18,13852,10165,Indiana,2005
27,"Switzerland County, IN",8-9.9,18155,18,13853,10151,Indiana,2006
28,"Switzerland County, IN",10-11.9,18155,18,13854,10271,Indiana,2007
29,"Switzerland County, IN",12-13.9,18155,18,13855,10387,Indiana,2008
...,...,...,...,...,...,...,...,...
56418,"Washington County, PA",14-15.9,42125,42,41446,208073,Pennsylvania,2011
56419,"Washington County, PA",16-17.9,42125,42,41447,208436,Pennsylvania,2012
56420,"Washington County, PA",16-17.9,42125,42,41448,208184,Pennsylvania,2013
56421,"Washington County, PA",18-19.9,42125,42,41449,208175,Pennsylvania,2014
56422,"Washington County, PA",18-19.9,42125,42,41450,208261,Pennsylvania,2015
56423,"Washington County, PA",20-21.9,42125,42,41451,207981,Pennsylvania,2016
56424,"Wayne County, PA",6-7.9,42127,42,41452,47133,Pennsylvania,1999
56425,"Wayne County, PA",6-7.9,42127,42,41453,47843,Pennsylvania,2000
56426,"Wayne County, PA",8-9.9,42127,42,41454,47994,Pennsylvania,2001
56427,"Wayne County, PA",8-9.9,42127,42,41455,48330,Pennsylvania,2002
56428,"Wayne County, PA",8-9.9,42127,42,41456,48938,Pennsylvania,2003
56429,"Wayne County, PA",10-11.9,42127,42,41457,49423,Pennsylvania,2004
56430,"Wayne County, PA",10-11.9,42127,42,41458,50409,Pennsylvania,2005
56431,"Wayne County, PA",10-11.9,42127,42,41459,52031,Pennsylvania,2006
56432,"Wayne County, PA",12-13.9,42127,42,41460,52341,Pennsylvania,2007
56433,"Wayne County, PA",12-13.9,42127,42,41461,51692,Pennsylvania,2008
56434,"Wayne County, PA",14-15.9,42127,42,41462,52552,Pennsylvania,2009
56435,"Wayne County, PA",14-15.9,42127,42,41463,52903,Pennsylvania,2010
56436,"Wayne County, PA",14-15.9,42127,42,41464,52237,Pennsylvania,2011
56437,"Wayne County, PA",16-17.9,42127,42,41465,51699,Pennsylvania,2012
56438,"Wayne County, PA",16-17.9,42127,42,41466,51640,Pennsylvania,2013
56439,"Wayne County, PA",18-19.9,42127,42,41467,51436,Pennsylvania,2014
56440,"Wayne County, PA",20-21.9,42127,42,41468,51198,Pennsylvania,2015
56441,"Wayne County, PA",20-21.9,42127,42,41469,50710,Pennsylvania,2016
56442,"Westmoreland County, PA",8-9.9,42129,42,41470,371248,Pennsylvania,1999
56443,"Westmoreland County, PA",8-9.9,42129,42,41471,369664,Pennsylvania,2000
56444,"Westmoreland County, PA",8-9.9,42129,42,41472,368698,Pennsylvania,2001
56445,"Westmoreland County, PA",10-11.9,42129,42,41473,367680,Pennsylvania,2002
56446,"Westmoreland County, PA",10-11.9,42129,42,41474,367836,Pennsylvania,2003
56447,"Westmoreland County, PA",10-11.9,42129,42,41475,367281,Pennsylvania,2004

In [16]:
ct_personal_income

,CT Income Tax,ID,Municipality,Number of Returns,Tax Per Capita,Tax Year
0,"$5,404,333.00",1,ANDOVER,"1,498","$3,608.00",2015
1,"$15,276,355.00",2,ANSONIA,"8,619","$1,772.00",2015
2,"$5,497,095.00",3,ASHFORD,"2,112","$2,603.00",2015
3,"$85,485,184.00",4,AVON,"8,361","$10,224.00",2015
4,"$5,961,156.00",5,BARKHAMSTED,"1,793","$3,325.00",2015
5,"$8,329,033.00",6,BEACON FALLS,"2,820","$2,954.00",2015
6,"$38,842,493.00",7,BERLIN,"10,021","$3,876.00",2015
7,"$13,537,388.00",8,BETHANY,"2,397","$5,648.00",2015
8,"$26,778,122.00",9,BETHEL,"8,657","$3,093.00",2015
9,"$5,575,338.00",10,BETHLEHEM,"1,648","$3,383.00",2015
10,"$35,172,834.00",11,BLOOMFIELD,"10,750","$3,272.00",2015
11,"$10,301,795.00",12,BOLTON,"2,351","$4,382.00",2015
12,"$3,455,854.00",13,BOZRAH,"1,194","$2,894.00",2015
13,"$58,571,911.00",14,BRANFORD,"14,144","$4,141.00",2015
14,"$59,200,924.00",15,BRIDGEPORT,"59,246",$999.00,2015
15,"$5,616,521.00",16,BRIDGEWATER,783,"$7,173.00",2015
16,"$64,129,600.00",17,BRISTOL,"28,518","$2,249.00",2015
17,"$32,729,473.00",18,BROOKFIELD,"7,896","$4,145.00",2015
18,"$7,924,397.00",19,BROOKLYN,"3,350","$2,365.00",2015
19,"$24,348,800.00",20,BURLINGTON,"4,224","$5,764.00",2015
20,"$3,468,291.00",21,CANAAN,"1,732","$2,002.00",2015
21,"$5,237,828.00",22,CANTERBURY,"2,287","$2,290.00",2015
22,"$26,369,747.00",23,CANTON,"4,629","$5,697.00",2015
23,"$2,158,328.00",24,CHAPLIN,983,"$2,196.00",2015
24,"$67,954,800.00",25,CHESHIRE,"12,241","$5,551.00",2015
25,"$7,575,384.00",26,CHESTER,"1,855","$4,084.00",2015
26,"$23,900,204.00",27,CLINTON,"6,241","$3,830.00",2015
27,"$26,116,776.00",28,COLCHESTER,"7,449","$3,506.00",2015
28,"$1,554,511.00",29,COLEBROOK,498,"$3,122.00",2015
29,"$9,267,192.00",30,COLUMBIA,"2,613","$3,547.00",2015
...,...,...,...,...,...,...
984,"$9,497,967.00",985,THOMASTON,"3,715","$2,557.00",2016
985,"$5,375,262.00",986,THOMPSON,"4,172","$1,288.00",2016
986,"$31,209,266.00",987,TOLLAND,"6,594","$4,733.00",2016
987,"$30,616,369.00",988,TORRINGTON,"16,108","$1,901.00",2016
988,"$82,832,975.00",989,TRUMBULL,"15,898","$5,210.00",2016
989,"$1,070,040.00",990,UNION,292,"$3,665.00",2016
990,"$36,128,414.00",991,VERNON,"14,576","$2,479.00",2016
991,"$2,648,992.00",992,VOLUNTOWN,"1,211","$2,187.00",2016
992,"$72,362,959.00",993,WALLINGFORD,"21,777","$3,323.00",2016
993,"$2,241,212.00",994,WARREN,428,"$5,236.00",2016
994,"$9,663,686.00",995,WASHINGTON,"1,820","$5,310.00",2016
995,"$54,183,281.00",996,WATERBURY,"46,280","$1,171.00",2016
996,"$31,294,806.00",997,WATERFORD,"9,581","$3,266.00",2016
997,"$32,969,740.00",998,WATERTOWN,"10,414","$3,166.00",2016
998,"$16,555,014.00",999,WESTBROOK,"3,237","$5,114.00",2016
999,"$171,817,664.00",1000,WEST HARTFORD,"28,558","$6,016.00",2016
1000,"$41,940,473.00",1001,WEST HAVEN,"24,394","$1,719.00",2016
1001,"$59,302,265.00",1002,WESTON,"4,087","$14,510.00",2016
1002,"$203,589,633.00",1003,WESTPORT,"11,623","$17,516.00",2016
1003,"$48,374,305.00",1004,WETHERSFIELD,"13,120","$3,687.00",2016
1004,"$7,934,980.00",1005,WILLINGTON,"2,636","$3,010.00",2016
1005,"$99,915,020.00",1006,WILTON,"7,519","$13,288.00",2016
1006,"$9,982,823.00",1007,WINCHESTER,"4,885","$2,044.00",2016
1007,"$12,456,754.00",1008,WINDHAM,"9,508","$1,310.00",2016
1008,"$39,080,521.00",1009,WINDSOR,"14,637","$2,670.00",2016
1009,"$13,790,875.00",1010,WINDSOR LOCKS,"6,444","$2,140.00",2016
1010,"$23,258,044.00",1011,WOLCOTT,"7,759","$2,998.00",2016
1011,"$42,737,698.00",1012,WOODBRIDGE,"4,128","$10,353.00",2016
1012,"$21,658,768.00",1013,WOODBURY,"4,712","$4,597.00",2016
1013,"$10,501,766.00",1014,WOODSTOCK,"3,592","$2,924.00",2016

In [10]:
ct_education_2014_2015.head(1)

,# of Distinctions,Accountability Index,Achievement Gap Flag,Category,Classification,DistrictCode,DistrictName,Grad6YrHNNHNDiff,Grad6YrRateHN,Grad6YrRateNHN,...,SchoolName,SchoolOrgType,SchoolTitleIType,State Category,Threshold_Mean_ELA,Threshold_Mean_Grad,Threshold_Mean_Math,Threshold_Mean_Sci,TotalPoints,TotalPossiblePoints
0,0,80.7,1.0,SchoolTot,None,740011,Litchfield School District,None,None,None,...,Litchfield High School_0746111,Public Schools,None,NaN,16.8,12.6,19.5,17.3,927.6,"1,150"

In [11]:
ct_unemployment.head(1)

,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,...,2011,2012,2013,2014,2015,2016,2017,2018,ID,Month
0,4.9,4.9,3.9,3.8,2.9,3.1,4.8,5.5,7.5,7.6,...,9.2,8.2,8.2,7.2,6.1,5.5,4.9,4.5,1,Jan

In [12]:
ct_accidental_drug_deaths.head(1)

,Age,AmendedMannerofDeath,Amphet,Any Opioid,Benzodiazepine,CaseNumber,Cocaine,Date,Death City,Death County,...,Morphine (not heroin),Other,Oxycodone,Oxymorphone,Race,Residence City,Residence County,Residence State,Sex,Tramad
0,46.0,None,None,None,Y,16-2335,Y,2016-06-21,LEDYARD,NEW LONDON,...,None,None,None,None,Black,LEDYARD,NEW LONDON,CT,Female,None